// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRKylZjwWmBIsGPuwUOnkHj-ftv8g4CAQ',
    appId: '1:787200665963:web:633be27d21dee4e1e4c42e',
    messagingSenderId: '787200665963',
    projectId: 'instagram-clone-1fd8f',
    authDomain: 'instagram-clone-1fd8f.firebaseapp.com',
    storageBucket: 'instagram-clone-1fd8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4HIB48Tqyhpl-SioBeIpkp_xpH1Bc9Q',
    appId: '1:787200665963:android:f17f60726e85b365e4c42e',
    messagingSenderId: '787200665963',
    projectId: 'instagram-clone-1fd8f',
    storageBucket: 'instagram-clone-1fd8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYtvz7DDa1hgB1CsXarIlJ7UFoVBDopI',
    appId: '1:787200665963:ios:281243980f267de0e4c42e',
    messagingSenderId: '787200665963',
    projectId: 'instagram-clone-1fd8f',
    storageBucket: 'instagram-clone-1fd8f.firebasestorage.app',
    iosBundleId: 'com.example.estatexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTYtvz7DDa1hgB1CsXarIlJ7UFoVBDopI',
    appId: '1:787200665963:ios:281243980f267de0e4c42e',
    messagingSenderId: '787200665963',
    projectId: 'instagram-clone-1fd8f',
    storageBucket: 'instagram-clone-1fd8f.firebasestorage.app',
    iosBundleId: 'com.example.estatexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCePM7lp-kNmiODUkFFCvARx0DDcZHPRqs',
    appId: '1:787200665963:web:b97b4f64f38078bde4c42e',
    messagingSenderId: '787200665963',
    projectId: 'instagram-clone-1fd8f',
    authDomain: 'instagram-clone-1fd8f.firebaseapp.com',
    storageBucket: 'instagram-clone-1fd8f.firebasestorage.app',
  );
}
